#Testing build
language: python
services:
- docker
sudo: required
env:
  global:
    - ENCRYPTION_KEY=ABCGDHEUSHFKIRMJSDFIUTEHFNGOWPOR
    - PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - docker build -t MukulMaheshwari/yaydoc .
  - docker run -d -p 127.0.0.1:80:4567 MukulMaheshwari/yaydoc /bin/sh -c "cd /root/yaydoc; bundle exec foreman start;"
  - docker ps -a
  - docker run MukulMaheshwari/yaydoc /bin/sh -c "cd /root/yaydoc; bundle exec rake test"

install:
  - nvm install 12.14.1
  - npm install
  - pip install -r requirements.txt
  - sudo apt-get install pandoc

script:
  - bash tests/generate_test.sh
  - python tests/test.py
  - npm run test

after_success:
  - bash kubernetes/travis/deploy.sh
  - bash kubernetes/travis/deploy-staging.sh
